Lumi-supercomputer/LUMI-EasyBuild-contrib

easybuild/easyconfigs/b/BLIS/BLIS-3.0.1-cpeGNU-21.08.eb

Added python code for partition based architecture options selection. 
Switching config_registry to `generic` I considered more reasonable for login nodes causes BLIS tests to fail. 
Another issue is with code I introduced to pass `conflict cray-libsci` to the module file: 
```
modluafooter = """
conflict("cray-libsci")
"""
```
It casues build process to fail because of loading fake module confict with already loaded cray-libsci. I do not understand it. Is this code wrong?

BLIS-3.0.1-cpeGNU-21.08 with partition awareness

---

easybuild/easyconfigs/a/Arm-Forge/Arm-Forge-22.0.eb

This needs to be improved. I am not sure how to resolve dependency on XCB (X11) library for GUI in the VNC container:
- Now it is taken from `X11` module but it is not resolved while `SINGULARITYENV_LD_LIBRARY_PATH` needs values to be evaluated and `$EBROOTX11` won't work; moreover it implicitly loads `cpeGNU` which may conflict with actual programming environment,
- XCB could be possibly added to the container but it contains 100+ libraries and may unnecessarily enlarge the container image
- XCB could be build with `system` toolchain but I am not sure if actually makes sense.

WIP Arm Forge initial easyconfig

---

easybuild/easyconfigs/s/singularity-bindings/singularity-bindings-system-cpeGNU-22.06.eb

Now `libmpi.so.12` is linked to `libcurl`. That introduces many libraries more.

Add `singularity-bindings` for `cpeGNU/22.06`

---

easybuild/easyconfigs/a/ABINIT/ABINIT-9.6.2-cpeGNU-21.12.eb

Add an extra environment variable: `HDF5_DISABLE_VERSION_CHECK=2` to avoid HDF5 version mismatch error. Adding `CRAY_LD_LIBRARY_PATH ` to `LD_LIBRARY_PATH ` works as well but the first solution is easier to implement in an easyconfig.

ABINIT/Workaround for HDF5 version mismatch

---

easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2-cpeGNU-22.06.eb
easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.3-cpeGNU-22.08.eb

This does a simple OpenMPI compilation mostly to launch containers with deep learning applications which will use RCCL as communication backend. I don't think we need to install it on the system. It can be installed locally by the users that needed.

Add OpenMPI recipe

---

easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.3-cpeGNU-22.08.eb

* I forgot to add `--with-pmi=/usr` in this version of the easyconfig
* `--with-slurm` is passed by default

Add the `--with-pmi` flag to the configuration

---

easybuild/easyconfigs/h/hipSYCL/hipSYCL-0.9.3-cpeGNU-22.08.eb

This receipt exports a default hipSYCL target for LUMI-G's GPUs.
Additionally, the accelerated CPU backend is disable due to
incompatibility between the ROCm version's LLVM and what hipSYCL
expects ([ref](https://github.com/illuhad/hipSYCL/blob/develop/doc/install-rocm.md)).

Add easyconfig for hipSYCL-0.9.3

---

easybuild/easyconfigs/c/CuPy/CuPy-11.0.0-cpeGNU-22.08.eb

Currently the cupy pip binaries don't support gfx90a.
This can be tested with https://github.com/Lumi-supercomputer/lumi-reframe-tests/pull/12.

Add easyconfig for cupy-11.0.0

---

easybuild/easyconfigs/n/Nek5000/Nek5000-19.0-cpeGNU-21.12.eb
easybuild/easyconfigs/n/Nek5000/README.md

This is easyconfig file for Reframe tests. It builds minimal set of tools required for case building (each simulation case requires specific build of Nek5000 binary executable).

Minimal Nek5000 build instruction

---

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2106-cpeGNU-21.08.eb
easybuild/easyconfigs/o/OpenFOAM/wmake-rules-linux64Cray.patch

Force `_GLIBCXX_USE_CXX11_ABI=0` macro, for C++ ABI consistency, in both build script and wmake rules (for later user code support). Resolves #46.

OpenFOAM unify cxx abi

---

easybuild/easyconfigs/e/ELPA/ELPA-2022.05.001-cpeCray-22.08-CPU.eb
easybuild/easyconfigs/e/ELPA/ELPA-2022.05.001-cpeGNU-22.08-CPU.eb

These are for the latest ELPA release (2022.05.001) with GNU and Cray compilers. The configs are CPU only versions to build GPU (ROCm) enabled on top of them. GNU version is essentially copy of the Kurt's config for previous release.
Issues:
* Cray version requires patches to build (add manual preprocessing option to the configure script and remove some broken sycl code),
* OpenMP compilation causes Cray Fortran compiler to segfault (therefore there is only non openmp version)
* TODO: cpeAMD version

Easyconfigs for latest ELPA release with GNU/Cray

---

easybuild/easyconfigs/s/spglib/spglib-1.16.3-cpeGNU-21.08.eb
easybuild/easyconfigs/s/spglib/spglib-1.16.3-cpeGNU-21.12.eb
easybuild/easyconfigs/s/spglib/spglib-1.16.3-cpeGNU-22.08.eb

Usage on CP2K EB recipe (cpeGNU 22.08) spglib was broken as it couldn't file the tarball. Upon further investigation it turns out that the url links to where spglib was being deployed had changed. The EB recipe has been updated to reflect this. 
Further testing with new EB in progress

Update spglib EB recipe

---

easybuild/easyconfigs/c/Charm++/Charm++-6.10.2-cpeGNU-22.08-MPI.eb
easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeGNU-22.08-MPI.eb

Adds `NAMD-2.14-cpeGNU-22.08-MPI.eb`, 
adapted from [`NAMD-2.14-cpeGNU-21.08-MPI.eb`](https://github.com/Lumi-supercomputer/LUMI-EasyBuild-contrib/blob/main/easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeGNU-21.08-MPI.eb). Also adds corresponding `Charm++-6.10.2-cpeGNU-22.08-MPI.eb`.
Tested a few minutes ago on `LUMI/C`.
Note: while trying to compile, I noticed that `cray-pmi-lib`, which was a dependency with `LUMI/21.08`, is now gone in `LUMI/22.08`, but that does not seems to affect the compilation procedure nor the running part, is this normal ?

Easyconfig for NAMD 2.14 on LUMI/22.08

---

easybuild/easyconfigs/h/h5py/LICENSE.md
easybuild/easyconfigs/h/h5py/README.md
easybuild/easyconfigs/h/h5py/h5py-3.7.0-cpeAMD-22.08-parallel.eb
easybuild/easyconfigs/h/h5py/h5py-3.7.0-cpeCray-22.08-parallel.eb
easybuild/easyconfigs/h/h5py/h5py-3.7.0-cpeGNU-22.08-parallel.eb
easybuild/easyconfigs/l/libxsmm/LICENSE.md
easybuild/easyconfigs/l/libxsmm/README.md
easybuild/easyconfigs/l/libxsmm/libxsmm-29Dec22-cpeCray-22.08.eb
easybuild/easyconfigs/l/libxsmm/libxsmm-29Dec22-cpeGNU-22.08.eb
easybuild/easyconfigs/m/Mako/LICENSE.md
easybuild/easyconfigs/m/Mako/Mako-1.2.0-cpeAMD-22.08.eb
easybuild/easyconfigs/m/Mako/Mako-1.2.0-cpeCray-22.08.eb
easybuild/easyconfigs/p/PyFR/LICENSE.md
easybuild/easyconfigs/p/PyFR/PyFR-1.15.0-cpeAMD-22.08-GPU.eb
easybuild/easyconfigs/p/PyFR/PyFR-1.15.0-cpeCray-22.08-CPU.eb
easybuild/easyconfigs/p/PyFR/PyFR-1.15.0-cpeCray-22.08-GPU.eb
easybuild/easyconfigs/p/PyFR/PyFR-1.15.0-cpeGNU-22.08-CPU.eb
easybuild/easyconfigs/p/PyFR/PyFR-1.15.0-cpeGNU-22.08-GPU.eb
easybuild/easyconfigs/p/PyFR/README.md
easybuild/easyconfigs/w/wheel/LICENSE.md
easybuild/easyconfigs/w/wheel/wheel-0.37.1-cpeAMD-22.08-cray-python3.9.eb
easybuild/easyconfigs/w/wheel/wheel-0.37.1-cpeCray-22.08-cray-python3.9.eb

PyFR for CPE 22.08 that include
- CPU version  (CPU suffix) for cpeCray and cpeGNU using the libxsmm OpenMP backend. PyFR requires a recent version of libxsmm for which no release exists, the date of the commit is used as the version.
- GPU version (GPU suffix) for cpeCray, cpeGNU and cpeAMD
Requested by RT#1284

Feature/PyFR for CPE 22.08

---

easybuild/easyconfigs/a/Amber/LICENSE.md
easybuild/easyconfigs/a/Amber/README.md
easybuild/easyconfigs/a/Amber/USER.md

To clarify that users are allowed to use CSC's Amber license for academic use.

Clarify Amber license and usage info

---

easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.9.0-cpeGNU-22.08-OpenMP.eb
easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.9.0-cpeGNU-22.08.eb

These are easyconfigs for ARPACK-NG. Two versions with and w/o OpenMP (in a sense of LibSci version), no EIGEN support, no Python support included.

Arpack library

---

easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.3-cpeGNU-22.08.eb

Remove ROCM version in the OpenMPI-4.1.3 recipe

---

easybuild/easyconfigs/h/hipfort/LICENSE.md
easybuild/easyconfigs/h/hipfort/README.md
easybuild/easyconfigs/h/hipfort/hipfort-0.4-0-cpeCray-22.08-rocm5.2.eb
easybuild/easyconfigs/h/hipfort/hipfort-0.4-0-cpeCray-22.08-rocm5.3.eb
easybuild/easyconfigs/h/hipfort/hipfort-0.4-0-cpeCray-22.12-rocm5.2.eb
easybuild/easyconfigs/h/hipfort/hipfort-0.4-0-cpeCray-23.03-rocm5.2.eb

hipfort  easyconfigs with cpeCray for codes that include a mix of OpenACC and HIP runtime calls.

Add hipfort for cpeCray

---

easybuild/easyconfigs/c/CGAL/CGAL-4.12.2-cpeGNU-22.12-OpenFOAM.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2106-cpeGNU-22.12.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2212-cpeGNU-22.12.eb

Simple update of OpenFOAM v21.06 for toolchain 22.12 and upgrade to v22.12. Additional CGAL dependency with the toolchain version updated to 22.12.

OpenFOAM for 22.12

---

easybuild/easyconfigs/t/Trilinos/README.md
easybuild/easyconfigs/t/Trilinos/Trilinos-12.18.1-cpeGNU-22.12.eb
easybuild/easyconfigs/t/Trilinos/trilinos-amesos-superlu-dist-6.4.patch
easybuild/easyconfigs/t/Trilinos/trilinos-amesos2-adapters-cce.patch
easybuild/easyconfigs/t/Trilinos/trilinos-boostlib-tpl-lib-list.patch
easybuild/easyconfigs/t/Trilinos/trilinos-fei-test-utils.patch
easybuild/easyconfigs/t/Trilinos/trilinos-stk-platform.patch
easybuild/easyconfigs/t/Trilinos/trilinos-stk-util-env.patch

This easyconfig is based on the old Cray's PE recipes for the latest release of Trilinos from version 12 branch. This version uses old API, still required by some codes. Tested in some extend on LUMI-C only. No GPU support. Major build issues description in the readme notes.

Trilinos 12.18.1 

---

easybuild/easyconfigs/s/SuperLU/SuperLU-6.0.0-cpeGNU-22.12-OpenMP.eb
easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.1.2-cpeGNU-22.12-OpenMP.eb

Two independent easyconfigs for SuperLU and SuperLU_DIST, recent versions for 22.12, explicit (with a name suffix) OpenMP support.

SuperLU and SuperLU_DIST easyconfigs for 22.12

---

easybuild/easyconfigs/b/Boost/Boost-1.72.0-cpeGNU-22.12.eb

Old Boost version 1.72.0 (without C++14 required) for Trilinos 12. Posting to contrib while outdated and only meant as specific dependency.

Downdate Boost v1.72.0 for Trilinos 12

---

easybuild/easyconfigs/g/GROMACS/USER.md

Added a chapter to point to the CSC installed version of GROMACS in the user.md file in software library

link to csc gromacs instructions

---

easybuild/easyconfigs/e/ELPA/ELPA-2023.05.001-cpeGNU-22.12-GPU.eb
easybuild/easyconfigs/e/ELPA/README.md
easybuild/easyconfigs/e/ELPA/elpa-2023.05.01.patch

This is a clean GPU recipe for the latest ELPA release. OpenMP not supported with AMD GPU stream implementation enabled.

ELPA 2023.05.001

---

easybuild/easyconfigs/c/CuPy/CuPy-12.2.0-cpeGNU-22.12.eb

Add recipe for cupy 12.2.0 based on the earlier 11.0.0 recipe by updating version numbers and fixing some paths.

Add CuPy 12.2.0

---

easybuild/easyconfigs/n/ncview/README.md
easybuild/easyconfigs/n/ncview/ncview-2.1.8-cpeAOCC-22.08.eb
easybuild/easyconfigs/n/ncview/ncview-2.1.8-cpeAOCC-22.12.eb
easybuild/easyconfigs/n/ncview/ncview-2.1.8-cpeCray-22.08.eb
easybuild/easyconfigs/n/ncview/ncview-2.1.8-cpeCray-22.12.eb
easybuild/easyconfigs/n/ncview/ncview-2.1.8-cpeGNU-22.08.eb
easybuild/easyconfigs/n/ncview/ncview-2.1.8-cpeGNU-22.12.eb

- Simple bump to CPE 22.12
- Switch back the CPE 22.08 easyconfigs download url to FTP: the fossie URL is no longer valid

Update NCView to 22.12 toolchains

---

easybuild/easyconfigs/c/COSMA/COSMA-2.6.6-cpeGNU-22.12-CPU.eb
easybuild/easyconfigs/c/CP2K/CP2K-2023.2-cpeGNU-22.12-CPU.eb
easybuild/easyconfigs/c/CP2K/LUMIC-20232.psmp
easybuild/easyconfigs/c/CP2K/README.md
easybuild/easyconfigs/c/CP2K/USER.md
easybuild/easyconfigs/l/libxc/libxc-6.2.2-cpeGNU-22.12.eb

Rebuilt and adapated the 2023.1 EB recipe for version 2023.2. This required reworking the COSMA EB file too. Updated the user documentation to reflect the new SLURM configuration for LUMI-G.

CP2K 2023.2 for CPE 22.12 with dependencies

---

easybuild/easyconfigs/n/nvtop/LICENSE.md
easybuild/easyconfigs/n/nvtop/README.md
easybuild/easyconfigs/n/nvtop/libudev.h
easybuild/easyconfigs/n/nvtop/nvtop-3.0.2.eb

This pull request add an easyconfig for nvtop, a (h)top like task monitor for AMD, Intel and NVIDIA GPUs. 
libudev, which is part of systemd is a dependency. LUMI has this library installed but not the libudev-devel package. To go around this problem, the file `libudev.h` is included as a patch to be used during compilation and the system libudev is linked to nvtop.

Add easyconfig for nvtop

---

easybuild/easyconfigs/g/GDAL/GDAL-3.5.3-cpeGNU-23.09-cray-python-3.10.10.eb
easybuild/easyconfigs/g/GDAL/GDAL-3.5.3-cpeGNU-23.09-noPython.eb
easybuild/easyconfigs/g/GDAL/README.md
easybuild/easyconfigs/g/GDAL/USER.md
easybuild/easyconfigs/g/GEOS/GEOS-3.12.1-cpeGNU-23.09.eb
easybuild/easyconfigs/g/GEOS/README.md
easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-cpeGNU-23.09.eb
easybuild/easyconfigs/h/HDF/README.md
easybuild/easyconfigs/l/libgeotiff/README.md
easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.7.1-cpeGNU-23.09.eb
easybuild/easyconfigs/versions-contrib-23.09.txt
easybuild/easyconfigs/x/Xerces-C++/LICENSE.md
easybuild/easyconfigs/x/Xerces-C++/README.md
easybuild/easyconfigs/x/Xerces-C++/USER.md
easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.5-cpeGNU-23.09.eb

We stuck to version 3.5.3 as this is the last version that builds with autotools. So far we failed to build newer versions with the CMake build process.

Enhanced GDAL module with dependencies for 23.09.

---

easybuild/easyconfigs/a/AdaptiveCpp/AdaptiveCpp-23.10.0-cpeAMD-23.09-rocm-5.2.3.eb
easybuild/easyconfigs/a/AdaptiveCpp/AdaptiveCpp-23.10.0-cpeAMD-23.09-rocm-5.6.1.eb
easybuild/easyconfigs/a/AdaptiveCpp/AdaptiveCpp-23.10.0-cpeGNU-22.12-rocm-5.2.3.eb
easybuild/easyconfigs/a/AdaptiveCpp/README.md

This is new release after project was renamed from hipSYCL.

AdaptiveCpp release 23.10.0

---

easybuild/easyconfigs/q/QUDA/QUDA-0a31b22-cpeAMD-22.09-GPU.eb
easybuild/easyconfigs/q/QUDA/QUDA-25102022-cpeAMD-22.08-GPU.eb

It was tested with tmLQCD project with rocm 5.2.3 and 5.3.3 but not earlier versions.

QUDA library for ROCm 5.3+

---

easybuild/easyconfigs/h/HyperQueue/HyperQueue-0.17.0.eb
easybuild/easyconfigs/h/HyperQueue/LICENSE.md
easybuild/easyconfigs/h/HyperQueue/README.md
easybuild/easyconfigs/h/HyperQueue/USER.md
easybuild/easyconfigs/r/Rust/README.md
easybuild/easyconfigs/r/Rust/Rust-1.75.0.eb
easybuild/easyconfigs/r/Rust/Rust-1.75_sysroot-fix-interpreter.patch

It also includes improved user documentation for HyperQueue for the LUMI Software Library.

Update HyperQueue and its build dependency Rust for 23.09

---

easybuild/easyconfigs/c/CP2K/USER.md

Using the instructions as provided on a clean installation result in the following error:
```
== Temporary log file in case of crash /run/user/327001883/easybuild/tmp/eb-up1fmr6g/easybuild-cuek8zyv.log
== processing EasyBuild easyconfig /appl/lumi/LUMI-EasyBuild-contrib/easybuild/easyconfigs/c/CP2K/CP2K-2023.1-cpeGNU-22.08-GPU.eb
== building and installing CP2K/2023.1-cpeGNU-22.08-GPU...
== fetching files...
== ... (took 1 secs)
== creating build dir, resetting environment...
== unpacking...
== ... (took 11 secs)
== patching...
== preparing...
== ... (took 6 secs)
== FAILED: Installation ended unsuccessfully (build directory: /run/user/327001883/easybuild/build/CP2K/2023.1/cpeGNU-22.08-GPU): build failed (first 300 chars): 
Missing modules for dependencies (use --robot?): …
```

Update USER.md for CP2K

---

easybuild/easyconfigs/d/DFTD4/DFTD4-3.4.0-cpeGNU-23.09.eb
easybuild/easyconfigs/l/libxc/libxc-6.1.0-cpeGNU-23.09-nofhc.eb
easybuild/easyconfigs/v/VASP/README.md
easybuild/easyconfigs/v/VASP/USER.md
easybuild/easyconfigs/v/VASP/VASP-6.4.2-cpeGNU-23.09-build01.eb
easybuild/easyconfigs/v/VASP/VASP-6.4.2-cpeGNU-23.09-build02.eb
easybuild/easyconfigs/v/VASP/makefile.include.VASP-6.4.2-cpeGNU-23.09-build01
easybuild/easyconfigs/v/VASP/makefile.include.VASP-6.4.2-cpeGNU-23.09-build02
easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-cpeGNU-23.09.eb

Updated builds of the latest VASP version 6.4.2 for CPE 23.09, incl dependencies. Both without custom source patches and with the I/O patches. Passes the VASP test suite. Only limited performance testing, but performance seems to be same as previous builds of 6.4.1

VASP 6.4.2 for CPE 23.09

---

easybuild/easyconfigs/c/Charm++/Charm++-7.0.0-cpeGNU-22.12-multicore.eb
easybuild/easyconfigs/n/NAMD/NAMD-3.0b4-cpeGNU-22.12-resident-GPU.eb
easybuild/easyconfigs/n/NAMD/NAMD-3.0b6-cpeAMD-23.09-rocm-5.6.1.eb
easybuild/easyconfigs/n/NAMD/README.md
easybuild/easyconfigs/n/NAMD/namd3-arch-rocm-clang.patch

This is recipe for NAMD 3.0b4 GPU resident build only. Supports only single node (no MPI at all) with Charm++ v7.0.0 multicore. Fails to build with `buildtools`. Not able to detect GPU P2P (hip) for unknown reason.

NAMD3 beta GPU resident version with Charm++

---

easybuild/easyconfigs/p/PETSc/PETSc-3.19.5-cpeCray-23.09-rocm-5.6.1.eb

This is to improve PETSc easyconfig for Cray toolchain and custom ROCm version. It needs LD_LIBRARY_PATH to be manually cleaned.

Fix for PETSc with ROCm/5.6.1

---

easybuild/easyconfigs/p/PyTorch/USER.md

The links will be dead when using them in the USER.md file in GitHub but were needed to make the documentation in the LUMI Software Library more readable.

Update PyTorch documentation. 

---

easybuild/easyconfigs/c/CuPy/CuPy-12.2.0-cpeGNU-22.09-rocm-5.2.3.eb
easybuild/easyconfigs/e/ELPA/ELPA-2023.11.001-cpeGNU-23.09-rocm-5.2.3.eb
easybuild/easyconfigs/g/GPAW/GPAW-24.1.0-cpeGNU-23.09-rocm-5.2.3.eb
easybuild/easyconfigs/g/GPAW/GPAW-24.1.0-cpeGNU-23.09.eb
easybuild/easyconfigs/g/GPAW/gpaw-gpu-disable-openmp.patch
easybuild/easyconfigs/g/GPAW/gpaw-update-lumi.patch

This is based on the instruction from @trossi https://gitlab.com/gpaw/gpaw/-/blob/7fa95475d156cbc77bb53332eec7d0a678321576/doc/platforms/Cray/lumi.rst
It also adds CuPy update for LUMI/23.09 with ROCm/5.2.3 and refined ELPA GPU recipe.  
Still some issues remain with the easyconfig:

GPAW recipe for LUMI

---

easybuild/easyconfigs/s/Score-P/README.md
easybuild/easyconfigs/s/Score-P/Score-P-8.4-cpeAMD-24.03-rocm.eb
easybuild/easyconfigs/s/Score-P/Score-P-8.4-cpeCray-24.03-rocm.eb
easybuild/easyconfigs/s/Score-P/Score-P-8.4-cpeCray-24.03.eb
easybuild/easyconfigs/s/Score-P/Score-P-8.4-cpeGNU-24.03.eb

This PR includes the easyconfigs for CPE 24.03. 
The cpeAOCC version is not included yet because the `make installcheck` fails. The cause of the failure is that some instrumentation that the test expects to be present is not present.

Score-P for CPE 24.03

---

easybuild/easyconfigs/l/LAMMPS/LAMMPS-2Aug2023_update3-cpeAMD-24.03-rocm.eb
easybuild/easyconfigs/l/LAMMPS/LAMMPS-2Aug2023_update3-cpeGNU-24.03-CPU.eb

As PLUMED has been updated to version 2.9.2 for GROMACS 2024.x support, we also need to update the LAMMPS recipes.

Update LAMMPS to use PLUMED 2.9.2

---

easybuild/easyconfigs/o/OTF2/OTF2-3.0.3-cpeAMD-24.03.eb
easybuild/easyconfigs/o/OTF2/OTF2-3.0.3-cpeAOCC-24.03.eb
easybuild/easyconfigs/o/OTF2/OTF2-3.0.3-cpeCray-24.03.eb
easybuild/easyconfigs/o/OTF2/OTF2-3.0.3-cpeGNU-24.03.eb
easybuild/easyconfigs/o/OTF2/README.md
easybuild/easyconfigs/s/Scalasca/README.md
easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.1-cpeAMD-24.03.eb
easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.1-cpeAOCC-24.03.eb
easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.1-cpeCray-24.03.eb
easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.1-cpeGNU-24.03.eb
easybuild/easyconfigs/s/Score-P/README.md
easybuild/easyconfigs/s/Score-P/Score-P-8.4-cpeAMD-24.03-rocm.eb
easybuild/easyconfigs/s/Score-P/Score-P-8.4-cpeAOCC-24.03.eb
easybuild/easyconfigs/s/Score-P/Score-P-8.4-cpeCray-24.03-rocm.eb
easybuild/easyconfigs/s/Score-P/Score-P-8.4-cpeCray-24.03.eb
easybuild/easyconfigs/s/Score-P/Score-P-8.4-installcheck-prevent-memory-optimization.patch

Heya,
first of all, thanks a lot for continuing to update the EasyConfigs I've provided a while back.
I've did some testing of the latest CPE/24.03 after the upgrade was finished and want to provide a few updates to the Score-P, OTF2 and Scalasca modules to bring them up-to-date with fixes and changes done upstream.
The PR includes the following changes:
- OTF2: Build Python bindings using the toolchain Python. See upstream PR https://github.com/easybuilders/easybuild-easyconfigs/pull/21325
- Score-P: Fix the installcheck failing for AOCC and do some smaller updates to indicate which toolchain was used.
- Scalasca: Just update the module for the new toolchain.
----
I've tested all these modules by installing them via EasyBuild on `partition/C`, `partition/L` and `partition/G`. The …

{perf}[LUMI/24.03] Changes to JSC tools

---

easybuild/easyconfigs/p/PETSc/PETSc-3.21.5-cpeGNU-24.03-rocm.eb

This provides clean recipe for building PETSc with Kokkos libraries as dependency modules.
Depends on #232

PETSC with external Kokkos libs 

---

easybuild/easyconfigs/l/libxc/README.md
easybuild/easyconfigs/l/libxc/libxc-6.2.2-cpeGNU-23.12.eb
easybuild/easyconfigs/l/libxc/libxc-6.2.2-cpeGNU-24.03.eb
easybuild/easyconfigs/l/libxc/libxc-7.0.0-cpeGNU-24.03.eb

See also https://github.com/easybuilders/easybuild-easyconfigs/issues/20417/

Removed the checksums of libxc as files are known to have changed over time

---

easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.8-cpeAMD-24.03.eb
easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.8-cpeAOCC-24.03.eb
easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.8-cpeCray-24.03.eb
easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.8-cpeGNU-24.03.eb
easybuild/easyconfigs/g/GOTCHA/LICENSE.md
easybuild/easyconfigs/g/GOTCHA/README.md

Adds GOTCHA v1.0.8, which is a new dependency for Score-P v9.0.
The main difference to upstream is that tests are disabled, due to some being sometimes flaky.

Add GOTCHA v1.0.8

---

easybuild/easyconfigs/c/CubeLib/CubeLib-4.9-cpeAMD-24.03.eb
easybuild/easyconfigs/c/CubeLib/CubeLib-4.9-cpeAOCC-24.03.eb
easybuild/easyconfigs/c/CubeLib/CubeLib-4.9-cpeCray-24.03.eb
easybuild/easyconfigs/c/CubeLib/CubeLib-4.9-cpeGNU-24.03.eb
easybuild/easyconfigs/c/CubeLib/README.md

Part of updating Score-P and Scalasca to latest releases.
Drops static library checks, as only shared or static libraries are built now.

Add CubeLib v4.9

---

easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.9-cpeAMD-24.03.eb
easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.9-cpeAOCC-24.03.eb
easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.9-cpeCray-24.03.eb
easybuild/easyconfigs/c/CubeWriter/CubeWriter-4.9-cpeGNU-24.03.eb

Part of updating Score-P and Scalasca to latest releases.
Drops static library checks, as only shared or static libraries are built now.

Add CubeWriter v4.9

---

easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.9-cpeAMD-24.03.eb
easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.9-cpeAOCC-24.03.eb
easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.9-cpeCray-24.03.eb
easybuild/easyconfigs/o/OPARI2/OPARI2-2.0.9-cpeGNU-24.03.eb

Part of updating Score-P and Scalasca to latest releases.
Just a minor version bump, required for a new flag to be recognized.

Add OPARI2 v2.0.9

---

easybuild/easyconfigs/o/OTF2/OTF2-3.1.1-cpeAMD-24.03.eb
easybuild/easyconfigs/o/OTF2/OTF2-3.1.1-cpeAOCC-24.03.eb
easybuild/easyconfigs/o/OTF2/OTF2-3.1.1-cpeCray-24.03.eb
easybuild/easyconfigs/o/OTF2/OTF2-3.1.1-cpeGNU-24.03.eb

Part of updating Score-P and Scalasca to latest releases.
Drops static library checks, as only shared or static libraries are built now.

Add OTF2 v3.1.1

---

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-12-cpeGNU-24.03-patch-20250206.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-12-cpeGNU-24.03.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-13-cpeGNU-24.03-master.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-13-cpeGNU-24.03-patch-20250911.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-13-cpeGNU-24.03.eb

Renaming old 12 and 13 EasyConfigs, deprecating the master versions and adding the last updates to version 12 and 13 in a way that users can easily do further updates.

Cleaning-up OpenFOAM 12 and 13

---

easybuild/easyconfigs/f/FUSE/FUSE-2.99.eb
easybuild/easyconfigs/l/libconfig/libconfig-1.7.3.eb
easybuild/easyconfigs/l/libcxi/libcxi-0f3609b.eb
easybuild/easyconfigs/l/libcxi/libcxi-shs-12.0.1.eb
easybuild/easyconfigs/l/libuv/libuv-1.48.0.eb
easybuild/easyconfigs/l/lm-sensors/lm-sensors-3.6.0.eb

This is recipe for `libcxi` from https://github.com/HewlettPackard/shs-libcxi and dependency libraries in specific versions. To be build with system toolchain and minimal other dependencies. Relies on additional HPE repos (for header files only):
- https://github.com/HewlettPackard/shs-cxi-driver
- https://github.com/HewlettPackard/shs-cassini-headers
This follows spack package configuration.

CXI library version SHS 12.0.1
