Lumi-supercomputer/LUMI-EasyBuild-contrib

- easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-cpeGNU-21.12.eb
Minor modification, changed download source from Github mirror to Gitlab source.
> Quantum Espresso 7.0 for cpeGNU 21.12

- easybuild/easyconfigs/c/CppUnit/CppUnit-1.15.1-cpeGNU-21.12.eb
Simple adaptation for LUMI toolchain
> cpp unit v. 1.15.1 for aria2

- easybuild/easyconfigs/c/CDO/CDO-2.0.5-cpeCray-21.12.eb
- easybuild/easyconfigs/c/CDO/CDO-2.0.5-cpeGNU-21.12.eb
- easybuild/easyconfigs/c/CDO/README.md
- easybuild/easyconfigs/c/CGAL/CGAL-4.12.2-cpeGNU-21.12-OpenFOAM.eb
- easybuild/easyconfigs/c/CMOR/CMOR-3.6.1-cpeAOCC-21.12.eb
- easybuild/easyconfigs/c/CMOR/CMOR-3.6.1-cpeCray-21.12.eb
- easybuild/easyconfigs/c/CMOR/CMOR-3.6.1-cpeGNU-21.12.eb
- easybuild/easyconfigs/c/CMOR/README.md
- easybuild/easyconfigs/e/ecCodes/README.md
- easybuild/easyconfigs/e/ecCodes/ecCodes-2.25.0-cpeAOCC-21.12.eb
- easybuild/easyconfigs/e/ecCodes/ecCodes-2.25.0-cpeCray-21.12.eb
- easybuild/easyconfigs/e/ecCodes/ecCodes-2.25.0-cpeGNU-21.12.eb
- easybuild/easyconfigs/j/json-c/README.md
- easybuild/easyconfigs/j/json-c/json-c-0.16-cpeAOCC-21.12.eb
- easybuild/easyconfigs/j/json-c/json-c-0.16-cpeCray-21.12.eb
- easybuild/easyconfigs/j/json-c/json-c-0.16-cpeGNU-21.12.eb
- easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-9-cpeGNU-21.12.eb
- easybuild/easyconfigs/o/OpenFOAM/README.md
- easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.2-cpeGNU-21.12.eb
- easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.4-cpeAOCC-21.12.eb
- easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.4-cpeCray-21.12.eb
- easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.4-cpeGNU-21.12.eb
- easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.0-cpeAOCC-21.12.eb
- easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.0-cpeCray-21.12.eb
- easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.0-cpeGNU-21.12.eb
- easybuild/easyconfigs/p/PLUMED/README.md
Some additional programs for the 21.12 CPE.
> Updates 21.12

- easybuild/easyconfigs/b/BCFtools/BCFtools-1.15.1-cpeGNU-21.12.eb
- easybuild/easyconfigs/b/BCFtools/README.md
- easybuild/easyconfigs/h/HTSlib/HTSlib-1.15.1-cpeGNU-21.12.eb
- easybuild/easyconfigs/h/HTSlib/README.md
- easybuild/easyconfigs/s/SAMtools/README.md
- easybuild/easyconfigs/s/SAMtools/SAMtools-1.15.1-cpeGNU-21.12.eb
Updated all SAMtools compoents to 1.15.1 after problems with 1.14 on LUMI (that are however likely not related to bugs in SAMtools.)
> Ht slib upgrade

- easybuild/easyconfigs/s/STRUMPACK/STRUMPACK-6.3.1-cpeGNU-22.08-CPU.eb
- easybuild/easyconfigs/s/STRUMPACK/STRUMPACK-6.3.1-cpeGNU-22.08-GPU.eb
Still missing the GPU version with HIP.
> Easyconfig for STRUMPACK 

- easybuild/easyconfigs/a/ADIOS2/ADIOS2-2.7.1-cpeGNU-22.08.eb
- easybuild/easyconfigs/a/ADIOS2/ADIOS2-2.7.1_fix-gcc11-include.patch
- easybuild/easyconfigs/a/ADIOS2/README.md
- easybuild/easyconfigs/l/LLVM/LLVM-14.0.6-cpeGNU-22.08.eb
- easybuild/easyconfigs/l/LLVM/README.md
- easybuild/easyconfigs/l/libglvnd/README.md
- easybuild/easyconfigs/l/libglvnd/libglvnd-1.4.0-cpeGNU-22.08.eb
- easybuild/easyconfigs/l/libsodium/README.md
- easybuild/easyconfigs/l/libsodium/libsodium-1.0.18-cpeGNU-22.08.eb
- easybuild/easyconfigs/m/Mako/Mako-1.2.0-cpeGNU-22.08.eb
- easybuild/easyconfigs/m/Mako/README.md
- easybuild/easyconfigs/m/Mesa/Mesa-22.2.1-cpeGNU-22.08.eb
- easybuild/easyconfigs/m/Mesa/README.md
- easybuild/easyconfigs/n/nlohmann-json/README.md
- easybuild/easyconfigs/n/nlohmann-json/nlohmann-json-3.10.4-cpeGNU-22.08.eb
- easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-cpeGNU-22.08.eb
- easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122_python3-compliant.patch
- easybuild/easyconfigs/o/OpenPGM/README.md
- easybuild/easyconfigs/p/ParaView/ParaView-5.10.1-cpeGNU-22.08.eb
- easybuild/easyconfigs/p/ParaView/ParaView-5.10.1_fix_FFmpeg_5.x_API_change.patch
- easybuild/easyconfigs/p/ParaView/README.md
- easybuild/easyconfigs/s/SZ/README.md
- easybuild/easyconfigs/s/SZ/SZ-2.1.12-cpeGNU-22.08.eb
- easybuild/easyconfigs/w/wheel/README.md
- easybuild/easyconfigs/w/wheel/wheel-0.37.1-cpeGNU-22.08-cray-python3.9.eb
- easybuild/easyconfigs/z/ZeroMQ/README.md
- easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.3.4-cpeGNU-22.08.eb
- easybuild/easyconfigs/z/zfp/README.md
- easybuild/easyconfigs/z/zfp/zfp-0.5.5-cpeGNU-22.08.eb
> Feature/Paraview and ADIOS2

- easybuild/easyconfigs/g/GROMACS/GROMACS-2021.1-cpeGNU-22.08-tMPI-GPU.eb
- easybuild/easyconfigs/g/GROMACS/GROMACS-2023-dev-cpeGNU-22.08-MPI-GPU.eb
This is basically the same as in: https://github.com/amd/InfinityHub-CI/blob/main/gromacs-docker/Dockerfile
MPI version I will update later.
> GROMACS unofficial HIP port from AMD

- easybuild/easyconfigs/j/jax/LICENSE.md
- easybuild/easyconfigs/j/jax/README.md
- easybuild/easyconfigs/j/jax/USER.md
- easybuild/easyconfigs/j/jax/jax-0.3.20-cpeCray-22.08-rocm5.2.eb
- easybuild/easyconfigs/j/jax/jax-0.3.20-cpeCray-22.12-rocm5.2.eb
- easybuild/easyconfigs/j/jax/jax-0.3.20-cpeCray-23.03-rocm5.2.eb
- easybuild/easyconfigs/j/jax/jax-0.3.20-cpeGNU-22.08-rocm5.2.eb
- easybuild/easyconfigs/j/jax/jax-0.3.20-cpeGNU-22.12-rocm5.2.eb
- easybuild/easyconfigs/j/jax/jax-0.4.1-cpeCray-22.08-rocm5.3.eb
- easybuild/easyconfigs/j/jax/jax-0.4.1-cpeGNU-22.08-rocm5.3.eb
- easybuild/easyconfigs/j/jax/jaxlib_local-tensorflow-repo.sed
- easybuild/easyconfigs/w/wheel/README.md
- easybuild/easyconfigs/w/wheel/wheel-0.38.4-cpeAMD-22.12-cray-python3.9.eb
- easybuild/easyconfigs/w/wheel/wheel-0.38.4-cpeCray-22.12-cray-python3.9.eb
- easybuild/easyconfigs/w/wheel/wheel-0.38.4-cpeCray-23.03-cray-python3.9.eb
- easybuild/easyconfigs/w/wheel/wheel-0.38.4-cpeGNU-22.12-cray-python3.9.eb
Depend on [#89](https://github.com/Lumi-supercomputer/LUMI-SoftwareStack/pull/89) as these easyconfigs use a custom LUMI easyblock.
> Add JAX 0.3.20 and 0.4.20

- easybuild/easyconfigs/m/mpiFileUtils/LICENSE.md
- easybuild/easyconfigs/m/mpiFileUtils/README.md
- easybuild/easyconfigs/m/mpiFileUtils/mpiFileUtils-0.11.1-cpeAMD-22.08.eb
- easybuild/easyconfigs/m/mpiFileUtils/mpiFileUtils-0.11.1-cpeAMD-22.12.eb
- easybuild/easyconfigs/m/mpiFileUtils/mpiFileUtils-0.11.1-cpeAOCC-22.08.eb
- easybuild/easyconfigs/m/mpiFileUtils/mpiFileUtils-0.11.1-cpeAOCC-22.12.eb
- easybuild/easyconfigs/m/mpiFileUtils/mpiFileUtils-0.11.1-cpeCray-22.08.eb
- easybuild/easyconfigs/m/mpiFileUtils/mpiFileUtils-0.11.1-cpeCray-22.12.eb
- easybuild/easyconfigs/m/mpiFileUtils/mpiFileUtils-0.11.1-cpeCray-23.03.eb
- easybuild/easyconfigs/m/mpiFileUtils/mpiFileUtils-0.11.1-cpeGNU-22.08.eb
- easybuild/easyconfigs/m/mpiFileUtils/mpiFileUtils-0.11.1-cpeGNU-22.12.eb
Add mpifileutils, a set of tools to replace traditional UNIX utilities with MPI based replacement
> Add Mpifileutils

- easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.23-cpeGNU-22.12-ILP64.eb
For lack of the support in the LibSci.
> Recent OpenBLAS with 64-bit integer support

- easybuild/easyconfigs/a/ADIOS2/ADIOS2-2.8.3-cpeGNU-22.12.eb
- easybuild/easyconfigs/a/ADIOS2/README.md
- easybuild/easyconfigs/l/libsodium/README.md
- easybuild/easyconfigs/l/libsodium/libsodium-1.0.18-cpeGNU-22.12.eb
- easybuild/easyconfigs/n/nlohmann-json/README.md
- easybuild/easyconfigs/n/nlohmann-json/nlohmann-json-3.11.2-cpeGNU-22.12.eb
- easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-cpeGNU-22.08.eb
- easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-cpeGNU-22.12.eb
- easybuild/easyconfigs/o/OpenPGM/README.md
- easybuild/easyconfigs/s/SZ/README.md
- easybuild/easyconfigs/s/SZ/SZ-2.1.12-cpeGNU-22.12.eb
- easybuild/easyconfigs/z/ZeroMQ/README.md
- easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.3.4-cpeGNU-22.12.eb
Update of the ADIOS2 package and its dependencies to cpeGNU 22.12 bumping version to 2.8.3.
> Update ADIOS2 to CPE 22.12

- easybuild/easyconfigs/s/seff/LICENSE.md
- easybuild/easyconfigs/s/seff/README.md
- easybuild/easyconfigs/s/seff/seff-22.05.8.eb
Add easyconfig for seff from Slurm 22.08.5
> seff 22.08.5

- easybuild/easyconfigs/h/hipSYCL/hipSYCL-0.9.4-cpeAMD-22.12-rocm-5.2.3.eb
- easybuild/easyconfigs/h/hipSYCL/hipSYCL-0.9.4-cpeGNU-22.12-rocm-5.2.3.eb
> Adds hipSYCL with cpeGNU and cpeAMD, closes #96.

- easybuild/easyconfigs/s/SCOTCH/SCOTCH-7.0.3-cpeGNU-22.12-int64.eb
This version is needed as dependency for custom builds of some applications.
> SCOTCH with support for 64-bit integers

- easybuild/easyconfigs/r/R/R-4.3.2-cpeGNU-23.09-raw.eb
- easybuild/easyconfigs/r/R/R-4.3.2-cpeGNU-23.09.eb
- easybuild/easyconfigs/r/R/README.md
- easybuild/easyconfigs/r/R/Rmpi-0.7-2_Cray.patch
- easybuild/easyconfigs/r/R/USER.md
The update was tested with the same examples as for 22.12.
> Update of the R EasyConfigs to 23.09

- easybuild/easyconfigs/h/Hypre/Hypre-2.26.0-cpeGNU-22.12.eb
- easybuild/easyconfigs/h/Hypre/Hypre-2.26.0-cpeGNU-23.09.eb
- easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.1-cpeGNU-23.09.eb
- easybuild/easyconfigs/p/PETSc/PETSc-3.19.5-cpeGNU-22.12.eb
- easybuild/easyconfigs/p/PETSc/PETSc-3.19.5-cpeGNU-23.09-GPU.eb
- easybuild/easyconfigs/s/SuperLU/SuperLU-6.0.0-cpeGNU-23.09-OpenMP.eb
- easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-8.1.2-cpeGNU-23.09-OpenMP.eb
This PETSc 3.19.5 recipe for LUMI/22.12 based on EPCC script from here https://github.com/ARCHER2-HPC/pe-scripts/blob/modules-2022-12/sh/petsc.sh
> PETSc 3.19.5

- easybuild/easyconfigs/d/DL_POLY_4/DL_POLY_4-5.1.0-cpeGNU-23.09.eb
- easybuild/easyconfigs/d/DL_POLY_4/DL_POLY_4-5.1.0-pre-cpeCray-23.09.eb
- easybuild/easyconfigs/d/DL_POLY_4/DL_POLY_4-5.2.0-pre-cpeGNU-23.09.eb
- easybuild/easyconfigs/d/DL_POLY_4/LICENSE.md
- easybuild/easyconfigs/d/DL_POLY_4/README.md
- easybuild/easyconfigs/d/DL_POLY_4/USER.md
Triggered by a ticket, but not sure about the quality. The code did not impress and manual, examples in the sources and CMake files did not correspond with one another.
> Some fairly bare-bones DL_POLY_4 EasyConfigs

- easybuild/easyconfigs/m/magma/LICENSE.md
- easybuild/easyconfigs/m/magma/README.md
- easybuild/easyconfigs/m/magma/magma-2.7.2-cpeAMD-23.09-rocm5.2.eb
- easybuild/easyconfigs/m/magma/magma-2.7.2-cpeCray-23.09-rocm5.2.eb
- easybuild/easyconfigs/m/magma/magma-2.7.2-cpeGNU-23.09-rocm5.2.eb
- easybuild/easyconfigs/m/magma/magma-2.7.2_crayftn-uppercase-module.patch
- easybuild/easyconfigs/m/magma/magma-2.7.2_separate-cxx-and-hip-compilation.patch
Easyconfigs for the magma library using CPE AMD, Cray and GNU.
> Magma for CPE 23.09 and ROCm 5.2

- easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-10-cpeGNU-23.09-20230119.eb
Add OpenFOAM v10. Confirmed to be working by user in ticket 4083
> OpenFOAM v10

- easybuild/easyconfigs/v/VASP/VASP-6.4.3-cpeGNU-24.03-build02.eb
- easybuild/easyconfigs/v/VASP/makefile.include.VASP-6.4.3-cpeGNU-24.03-build02
> Update for VASP with 24.03

- easybuild/easyconfigs/c/CP2K/LUMIC-20242.psmp
- easybuild/easyconfigs/c/CP2K/LUMIG-20242.psmp
modified the psmp to:
1-    remove MPI_2008 (credits to Alfio)
2-    fix gpu backend by removing SPLA library
2.5- rework LUMIG psmp to add libraries individually
> fix problem with new stack on CP2K, errors coming from ticket 5335 and 4753

- easybuild/easyconfigs/c/CP2K/LUMIG-20242.psmp
- easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-cpeGNU-24.03.eb
update libxsmm base repo to pull. Old one is not found anymore
> update repo for libxsmm

- easybuild/easyconfigs/f/feh/feh-2.26-cpeGNU-24.03.eb
- easybuild/easyconfigs/i/Imlib2/Imlib2-1.5.1-cpeGNU-24.03.eb
This consists of `Imlib2` and `feh`
> Basic X image viewers

- easybuild/easyconfigs/d/DFTD4/DFTD4-3.4.0-cpeGNU-24.03.eb
- easybuild/easyconfigs/l/libxc/libxc-7.0.0-cpeGNU-24.03-nofhc.eb
- easybuild/easyconfigs/v/VASP/POTCAR-readonly-650.patch
- easybuild/easyconfigs/v/VASP/USER.md
- easybuild/easyconfigs/v/VASP/VASP-6.5.0-cpeGNU-24.03-build01.eb
- easybuild/easyconfigs/v/VASP/VASP-6.5.0-cpeGNU-24.03-build02.eb
- easybuild/easyconfigs/v/VASP/makefile.include.VASP-6.5.0-cpeGNU-24.03-build01
- easybuild/easyconfigs/v/VASP/makefile.include.VASP-6.5.0-cpeGNU-24.03-build02
Added files to update easyconfigs for vasp 6.5.0, fixed up the documentation and removed references to older vasp.
Also includes VASP dependancies
> Updated vasp to 6.5.0

- easybuild/easyconfigs/v/VASP/README.md
Update the README.md file in the VASP directory to reflect the new version.
> Vasp 6.5.0 cleanup

- easybuild/easyconfigs/p/PETSc/PETSc-3.21.5-cpeGNU-24.03-rocm.eb
> Fix for missing Kokkos libraries

- easybuild/easyconfigs/w/Wannier90/README.md
- easybuild/easyconfigs/w/Wannier90/Wannier90-24Jan2025-cpeGNU-24.03.eb
This is to address issue  https://github.com/wannier-developers/wannier90/issues/521 for which fix from https://github.com/easybuilders/easybuild-easyconfigs/pull/21383 does not help on LUMI.
> Wannier90 develop version

- easybuild/easyconfigs/k/Kokkos-kernels/Kokkos-kernels-4.5.1-cpeAMD-24.03-rocm.eb
- easybuild/easyconfigs/k/Kokkos-kernels/Kokkos-kernels-4.5.1-cpeGNU-24.03-rocm.eb
- easybuild/easyconfigs/k/Kokkos/Kokkos-4.5.1-cpeAMD-24.03-rocm.eb
- easybuild/easyconfigs/k/Kokkos/Kokkos-4.5.1-cpeGNU-24.03-rocm.eb
Kokkos 4.5.01 with OpenMP (host) and HIP (device).
> Kokkos and friends

- easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.2-cpeAMD-24.03.eb
- easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.2-cpeAOCC-24.03.eb
- easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.2-cpeCray-24.03.eb
- easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.2-cpeGNU-24.03.eb
> Add Scalasca 2.6.2

- easybuild/easyconfigs/l/Libint-CP2K/Libint-CP2K-2.7.2-cpeGNU-25.03.eb
> Libint CP2K 25.03

- easybuild/easyconfigs/l/libxc/libxc-7.0.0-cpeGNU-25.03.eb
> libxc 25.03

- easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-cpeGNU-25.03.eb
> Libxsmm 25.03

- easybuild/easyconfigs/c/CP2K/CP2K-2024.2-cpeGNU-25.03-CPU.eb
Update for CP2K cpu version to CPE 25.03
> CP2K 25.03

- easybuild/easyconfigs/v/VASP/VASP-6.5.1-cpeGNU-24.03-build02.eb
- easybuild/easyconfigs/v/VASP/makefile.include.VASP-6.5.1-cpeGNU-24.03-build02
I’m new to EasyBuild and contributing as a begginer here, so please let me know if adjustments are needed.
This is a straightforward addition of VASP 6.5.1 for the LUMI 24.03 toolchain, based on previous easyconfig and patch.
The installation works as expected.
I'd appreciate feedback and guidance!
> Add VASP 6.5.1 EasyBuild config for LUMI 24.03

- easybuild/easyconfigs/c/Cython/Cython-3.1.2-cpeGNU-25.03.eb
This is refined version w/o unnecessary extensions.
> Cython 3 update for 25.03
